---
- name: Deploy AWS Infrastructure, EKS, and Prometheus
  hosts: localhost
  gather_facts: no
  vars:
    aws_region: us-east-1
    cluster_name: my-eks-cluster
    prometheus_namespace: monitoring
    instance_type: t3.medium
    node_group_name: eks-node-group
    desired_capacity: 2
    max_size: 3
    min_size: 1

  tasks:
    - name: Include EKS role
      include_role:
        name: eks

    - name: Include Prometheus role
      include_role:
        name: prometheus

